#portable posix makefile generated by g2b

CC = clang

PKG_CFLAGS != pkg-config --cflags wayland-client xkbcommon pixman-1 fontconfig freetype2
PKG_LIBS != pkg-config --libs wayland-client xkbcommon pixman-1 fontconfig freetype2

CFLAGS = -g -O2 -Wall -Wno-unused-variable -Wno-unused-function \
         -DPLAN9PORT -D_DEFAULT_SOURCE -D_BSD_SOURCE \
         -I. -I$(PLAN9)/include -I./protocol -I./shim -I./acme \
         $(PKG_CFLAGS)

LDFLAGS = -L$(PLAN9)/lib
LIBS = -Wl,--start-group -lplumb -l9pclient -lmux -lcomplete -lbio -lframe -lthread -l9 -Wl,--end-group \
       -lwld \
       -ldrm -ldrm_intel -ldrm_nouveau \
       $(PKG_LIBS) \
       -lcrypto -lpthread -lm -lrt

SHIMOBJS = shim/draw/core.o shim/draw/paint.o shim/draw/font.o shim/draw/geom.o \
           shim/draw/input.o shim/draw/window.o shim/draw/snarf.o \
           shim/wayland.o shim/input.o shim/clipboard.o protocol/xdg-shell-protocol.o

ACMEOBJS = acme/acme.o acme/addr.o acme/buff.o acme/cols.o acme/disk.o \
           acme/ecmd.o acme/edit.o acme/elog.o acme/exec.o acme/file.o \
           acme/fsys.o acme/logf.o acme/look.o acme/regx.o acme/rows.o \
           acme/scrl.o acme/text.o acme/time.o acme/util.o acme/wind.o \
           acme/xfid.o acme/sha1.o

MAILOBJS = acme/mail/html.o acme/mail/mail.o acme/mail/mesg.o \
           acme/mail/reply.o acme/mail/util.o acme/mail/win.o

.PHONY: all clean test

all: wave acme/mail/Mail

config.h: config.def.h
	cp $< $@

shim/draw/core.o: shim/draw/core.c
	$(CC) $(CFLAGS) -c shim/draw/core.c -o shim/draw/core.o

shim/draw/paint.o: shim/draw/paint.c config.h
	$(CC) $(CFLAGS) -c shim/draw/paint.c -o shim/draw/paint.o

shim/draw/font.o: shim/draw/font.c config.h
	$(CC) $(CFLAGS) -c shim/draw/font.c -o shim/draw/font.o

shim/draw/geom.o: shim/draw/geom.c
	$(CC) $(CFLAGS) -c shim/draw/geom.c -o shim/draw/geom.o

shim/draw/input.o: shim/draw/input.c
	$(CC) $(CFLAGS) -c shim/draw/input.c -o shim/draw/input.o

shim/draw/window.o: shim/draw/window.c
	$(CC) $(CFLAGS) -c shim/draw/window.c -o shim/draw/window.o

shim/draw/snarf.o: shim/draw/snarf.c
	$(CC) $(CFLAGS) -c shim/draw/snarf.c -o shim/draw/snarf.o

shim/wayland.o: shim/wayland.c config.h
	$(CC) $(CFLAGS) -c shim/wayland.c -o shim/wayland.o

shim/input.o: shim/input.c
	$(CC) $(CFLAGS) -c shim/input.c -o shim/input.o

shim/clipboard.o: shim/clipboard.c shim/shim.h shim/wayland-state.h
	$(CC) $(CFLAGS) -c shim/clipboard.c -o shim/clipboard.o

protocol/xdg-shell-protocol.o: protocol/xdg-shell-protocol.c
	$(CC) $(CFLAGS) -c protocol/xdg-shell-protocol.c -o protocol/xdg-shell-protocol.o

acme/acme.o: acme/acme.c acme/dat.h acme/fns.h config.h
	$(CC) $(CFLAGS) -c acme/acme.c -o acme/acme.o

acme/addr.o: acme/addr.c acme/dat.h acme/fns.h
	$(CC) $(CFLAGS) -c acme/addr.c -o acme/addr.o

acme/buff.o: acme/buff.c acme/dat.h acme/fns.h
	$(CC) $(CFLAGS) -c acme/buff.c -o acme/buff.o

acme/cols.o: acme/cols.c acme/dat.h acme/fns.h
	$(CC) $(CFLAGS) -c acme/cols.c -o acme/cols.o

acme/disk.o: acme/disk.c acme/dat.h acme/fns.h
	$(CC) $(CFLAGS) -c acme/disk.c -o acme/disk.o

acme/ecmd.o: acme/ecmd.c acme/dat.h acme/fns.h acme/edit.h
	$(CC) $(CFLAGS) -c acme/ecmd.c -o acme/ecmd.o

acme/edit.o: acme/edit.c acme/dat.h acme/fns.h acme/edit.h
	$(CC) $(CFLAGS) -c acme/edit.c -o acme/edit.o

acme/elog.o: acme/elog.c acme/dat.h acme/fns.h acme/edit.h
	$(CC) $(CFLAGS) -c acme/elog.c -o acme/elog.o

acme/exec.o: acme/exec.c acme/dat.h acme/fns.h
	$(CC) $(CFLAGS) -c acme/exec.c -o acme/exec.o

acme/file.o: acme/file.c acme/dat.h acme/fns.h
	$(CC) $(CFLAGS) -c acme/file.c -o acme/file.o

acme/fsys.o: acme/fsys.c acme/dat.h acme/fns.h
	$(CC) $(CFLAGS) -c acme/fsys.c -o acme/fsys.o

acme/logf.o: acme/logf.c acme/dat.h acme/fns.h
	$(CC) $(CFLAGS) -c acme/logf.c -o acme/logf.o

acme/look.o: acme/look.c acme/dat.h acme/fns.h
	$(CC) $(CFLAGS) -c acme/look.c -o acme/look.o

acme/regx.o: acme/regx.c acme/dat.h acme/fns.h
	$(CC) $(CFLAGS) -c acme/regx.c -o acme/regx.o

acme/rows.o: acme/rows.c acme/dat.h acme/fns.h
	$(CC) $(CFLAGS) -c acme/rows.c -o acme/rows.o

acme/scrl.o: acme/scrl.c acme/dat.h acme/fns.h
	$(CC) $(CFLAGS) -c acme/scrl.c -o acme/scrl.o

acme/text.o: acme/text.c acme/dat.h acme/fns.h
	$(CC) $(CFLAGS) -c acme/text.c -o acme/text.o

acme/time.o: acme/time.c acme/dat.h acme/fns.h
	$(CC) $(CFLAGS) -c acme/time.c -o acme/time.o

acme/util.o: acme/util.c acme/dat.h acme/fns.h
	$(CC) $(CFLAGS) -c acme/util.c -o acme/util.o

acme/wind.o: acme/wind.c acme/dat.h acme/fns.h
	$(CC) $(CFLAGS) -c acme/wind.c -o acme/wind.o

acme/xfid.o: acme/xfid.c acme/dat.h acme/fns.h
	$(CC) $(CFLAGS) -c acme/xfid.c -o acme/xfid.o

acme/sha1.o: acme/sha1.c acme/dat.h acme/fns.h
	$(CC) $(CFLAGS) -c acme/sha1.c -o acme/sha1.o

wave: $(SHIMOBJS) $(ACMEOBJS)
	$(CC) -o wave $(SHIMOBJS) $(ACMEOBJS) $(LDFLAGS) $(LIBS)

acme/mail/html.o: acme/mail/html.c acme/mail/dat.h
	$(CC) $(CFLAGS) -c acme/mail/html.c -o acme/mail/html.o

acme/mail/mail.o: acme/mail/mail.c acme/mail/dat.h
	$(CC) $(CFLAGS) -c acme/mail/mail.c -o acme/mail/mail.o

acme/mail/mesg.o: acme/mail/mesg.c acme/mail/dat.h
	$(CC) $(CFLAGS) -c acme/mail/mesg.c -o acme/mail/mesg.o

acme/mail/reply.o: acme/mail/reply.c acme/mail/dat.h
	$(CC) $(CFLAGS) -c acme/mail/reply.c -o acme/mail/reply.o

acme/mail/util.o: acme/mail/util.c acme/mail/dat.h
	$(CC) $(CFLAGS) -c acme/mail/util.c -o acme/mail/util.o

acme/mail/win.o: acme/mail/win.c acme/mail/dat.h
	$(CC) $(CFLAGS) -c acme/mail/win.c -o acme/mail/win.o

acme/mail/Mail: $(MAILOBJS)
	$(CC) -o acme/mail/Mail $(MAILOBJS) $(LDFLAGS) $(LIBS)

test-shim: test-shim.o $(SHIMOBJS)
	$(CC) -o test-shim test-shim.o $(SHIMOBJS) $(LDFLAGS) $(LIBS)

test-shim.o: test-shim.c
	$(CC) $(CFLAGS) -c test-shim.c -o test-shim.o

clean:
	rm -f $(SHIMOBJS) $(ACMEOBJS) $(MAILOBJS) wave acme/mail/Mail test-shim test-shim.o

install: wave
	install -D wave /usr/bin/wave

